# Generated by Django 6.0.3 on 2026-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_options_women_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
